### ISSUE TITLE
Terminal.app requires confirmation when closing

### ISSUE THREAD

**Issue by slava-kuksa-op** [qparis/FinderOpenTerminal#2]
Terminal.app asks for confirmation to terminate 2 running bash processes on closing when it was opened using Open Terminal on Mac OS X 10.11.5

<img width="573" alt="screen shot 2016-07-07 at 9 21 46 pm" src="https://cloud.githubusercontent.com/assets/20247469/16664566/44d97f7a-4489-11e6-9af9-16f6aded9bd5.png">

**Comment by 153957** [comment]
This is affected by the settings at Terminal -> Preferences -> Profiles -> [Default] -> Shell -> Ask before closing.

_edit_: I see this program opens the Terminal in a different way than normally, e.g. does not execute `.bash_profile`. That probably causes this..

**Comment by B-Lach** [comment]
Is it really necessary to execute the script at `/tmp/openTerminal` to open a new terminal window?

`open -b com.apple.terminal -n --args cd /your/path/goes/here` is everything i have to do to open the window + no confirmation alert.

I've already replaced the 
`do {...} catch _ {...}`
 with 
`SwiftySystem.execute("/usr/bin/open", arguments: ["-b", "com.apple.terminal", "-n", "--args", "cd", url.path])`
and it's working fine.

**Comment by qparis** [comment]
Does it work when the terminal is already opened?

**Comment by B-Lach** [comment]
It is working BUT each opened window is a new process of Terminal.app.
So it isn't the best solution atm.

<img width="133" alt="bildschirmfoto 2016-10-29 um 21 45 35" src="https://cloud.githubusercontent.com/assets/5971602/19832315/4f8fcb8a-9e21-11e6-84e8-abf969e310e1.png">

**Comment by B-Lach** [comment]
[Worked it out](https://github.com/B-Lach/FinderOpenTerminal/commit/3c7e0fb6d5dea10127ba614c271051ba939da36a), I guess.
Is working  now as expected: only one process, works if a terminal window is already open and if Terminal.app isn't running as well

**Comment by qparis** [comment]
Does it work if the directory contains spaces?

**Comment by B-Lach** [comment]
Obviously directories containing spaces is working now 😎 Before requesting a new pull request could you explain, what the script at /tmp/openTerminal is actually doing? `cd`should be clear but I've no idea what the rest of script is meant for.

**Update**

Ok, researched it by myself: 
You explicitly running a new interactive shell using bash and the corresponding profile. This means if someone changed the shell to ksh using the command `chsh -s /bin/ksh` permanently, it will be ignored using your way to open a new terminal. The way I've implemented it, the new window is  running a login shell using the shell set by the user. #1 would also be 'fixed' because the new shell is the users expected shell.

Output using your way:
<img width="429" alt="bildschirmfoto 2016-11-02 um 13 39 51" src="https://cloud.githubusercontent.com/assets/5971602/19930194/90eb2e4c-a107-11e6-81ce-ffc26b417062.png">

Output using Applescript:
<img width="296" alt="bildschirmfoto 2016-11-02 um 14 23 28" src="https://cloud.githubusercontent.com/assets/5971602/19930272/f697de02-a107-11e6-8401-7c178adf85f5.png">

**Comment by saurabhshri** [comment]
So @B-Lach could you share `.app` where it doesn't require confirmation when closing?

Also, @qparis any plan on adding it to upstream?

**Comment by qparis** [comment]
Feel free to send any pull request :-)

**Comment by qparis** [comment]
Upstream has been updated to compile on Swift 4.1
Any news about this issue?

**Comment by qparis** [comment]
(Should be fixed by the way)
